# Generated by Django 4.2.6 on 2023-10-23 08:33

from django.db import migrations, models
import live_statistic_app.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('live_statistic_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_overal_statistic',
            fields=[
                ('customer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('cust_avg_time', models.IntegerField()),
                ('cust_avg_page', models.IntegerField()),
                ('cust_avg_clicks', models.IntegerField()),
                ('cust_avg_cta', models.IntegerField()),
                ('cust_total_num_sessions', models.IntegerField()),
                ('cust_total_num_landing', models.IntegerField()),
                ('cust_total_num_contact', models.IntegerField()),
                ('cust_total_num_pricing', models.IntegerField()),
                ('cust_total_num_signin', models.IntegerField()),
                ('cust_total_num_beforepurchase', models.IntegerField()),
                ('cust_total_num_purchase', models.IntegerField()),
                ('cust_advisory_proc', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('cust_lifecycle', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')])),
                ('cust_ranking', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('cust_activity', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('cust_last_time', live_statistic_app.fields.YearValueField()),
            ],
        ),
        migrations.CreateModel(
            name='Sessions_overal_statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('session_time', models.IntegerField()),
                ('session_number_of_pages', models.IntegerField()),
                ('session_number_of_clicks', models.IntegerField()),
                ('session_number_of_cta', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='account',
        ),
    ]
