# Generated by Django 4.2.6 on 2023-10-23 09:47

from django.db import migrations, models
import overal_statistic_app.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('overal_statistic_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_overal_statistic',
            name='id',
        ),
        migrations.AlterField(
            model_name='customer_overal_statistic',
            name='cust_activity',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
        migrations.AlterField(
            model_name='customer_overal_statistic',
            name='cust_advisory_proc',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')]),
        ),
        migrations.AlterField(
            model_name='customer_overal_statistic',
            name='cust_avg_clicks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer_overal_statistic',
            name='cust_last_time',
            field=overal_statistic_app.fields.YearValueField(),
        ),
        migrations.AlterField(
            model_name='customer_overal_statistic',
            name='cust_lifecycle',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')]),
        ),
        migrations.AlterField(
            model_name='customer_overal_statistic',
            name='cust_ranking',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
        migrations.AlterField(
            model_name='customer_overal_statistic',
            name='customer_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sessions_overal_statistic',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
